### ISSUE TITLE
Console note --> Session Note

### ISSUE THREAD

**Issue by lmperry** [scitran-apps/dicom-mr-classifier#10]
If an operator enters a note on the console we should add that note to the session. There are many examples of this. One of those examples can be used to determine the following:

- [ ] Which field in the DICOM stores such notes?
- [ ] Can the system attribute the note to either itself, or the operator? 
- [ ] Metadata for inserting this note on the session

**Comment by jenreiter** [comment]
I want to make sure that I understand this issue...

**Comment by jenreiter** [comment]
Addressing the first checkbox, a field in the DICOM that could be a good place to store a comment or note would be (0020,4000) ImageComments.
