### ISSUE TITLE
Improve classifier for BIDS client

### ISSUE THREAD

**Issue by jenreiter** [scitran-apps/dicom-mr-classifier#15]
The following improvements to the file `measurement-from-label.py` need to be implemented to correctly allow for BIDS client to run on the customer test dataset:

1) In function, `is_fieldmap `, add regex to match to string 'distortion'
2) In function, `is_functional`, change '\_task\_' to 'task'
3) The string 'FMRI_DISTORTION_AP_2mm_66sl' needs to be classified as fieldmap, currently it is incorrectly being classified as functional

**Comment by lmperry** [comment]
Cosed by: 3a91f4b
