### ISSUE TITLE
Measurement should be set to "Non-Image" if the dicom files do not contain image data

### ISSUE THREAD

**Issue by ryansanford** [scitran-apps/dicom-mr-classifier#8]
https://github.com/scitran/core/issues/402#issuecomment-315910944

Rather than making decision based upon SOP Class UID, suggest checking the presence of the pixel data tag (7FE0, 0010)

**Comment by jenreiter** [comment]
@ryansanford I wanted to clarify before I push the change, is the "measurement" supposed to be set to "Non-Image" or the "intent"? Issue description here says measurement but [scitran/core#402 (comment)](https://github.com/scitran/core/issues/402#issuecomment-315910944) states "Added Non-Image intent." I was working on the classification branch where "intent" is being used but I see on the master branch, "measurement" is being used. I'm assuming I should actually be working off master...

**Comment by ryansanford** [comment]
@jenreiter We need to address in parallel. New branch off master using metadata key "measurement", and similar off the classification branch using key "intent". Classification branch won't land or be released until the dependent work in scitran/core lands.
